//
//  EzLearn.h
//  ezLearn
//
//  Created by Ade Ijidakinro on 4/21/15.
//  Copyright (c) 2015 Dephyned. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface EzLearn : NSObject

// Drawing Methods
+ (void)drawCanvas1WithFrame: (CGRect)frame;
+ (void)drawCanvas2WithFrame: (CGRect)frame;

@end
