//
//  EzLearn.m
//  ezLearn
//
//  Created by Ade Ijidakinro on 4/21/15.
//  Copyright (c) 2015 Dephyned. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "EzLearn.h"


@implementation EzLearn

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1WithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* fillColor = [UIColor colorWithRed: 0.4 green: 0.4 blue: 0.4 alpha: 0.902];


    //// Subframes
    CGRect history6svgGroup = CGRectMake(CGRectGetMinX(frame), CGRectGetMinY(frame) - 0.25, CGRectGetWidth(frame), CGRectGetHeight(frame) + 0.5);


    //// history6.svg Group
    {
        //// Group 2
        {
            //// history
            {
                //// Bezier Drawing
                UIBezierPath* bezierPath = UIBezierPath.bezierPath;
                [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.52500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.00000 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.11500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.25263 * CGRectGetHeight(history6svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.35000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.00000 * CGRectGetHeight(history6svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.19500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.10000 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.00000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.13158 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.00000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.47368 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.32500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.47368 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.18500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.32632 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.52500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.10526 * CGRectGetHeight(history6svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.25000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.19474 * CGRectGetHeight(history6svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.37500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.10526 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.90000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.50000 * CGRectGetHeight(history6svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.73000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.10526 * CGRectGetHeight(history6svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.90000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.28421 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.52500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.89474 * CGRectGetHeight(history6svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.90000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.71579 * CGRectGetHeight(history6svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.73000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.89474 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.17000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.63158 * CGRectGetHeight(history6svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.36000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.89474 * CGRectGetHeight(history6svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.22500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.78421 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.06500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.63158 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.52500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 1.00000 * CGRectGetHeight(history6svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.12000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.84211 * CGRectGetHeight(history6svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.30500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 1.00000 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 1.00000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.50000 * CGRectGetHeight(history6svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.79000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 1.00000 * CGRectGetHeight(history6svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(history6svgGroup) + 1.00000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.77368 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.52500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.00000 * CGRectGetHeight(history6svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(history6svgGroup) + 1.00000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.22632 * CGRectGetHeight(history6svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.78500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.00000 * CGRectGetHeight(history6svgGroup))];
                [bezierPath closePath];
                [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.45000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.26316 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.45000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.53158 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.68500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.67895 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.72500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.61053 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.52500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.48421 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.52500 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.26316 * CGRectGetHeight(history6svgGroup))];
                [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(history6svgGroup) + 0.45000 * CGRectGetWidth(history6svgGroup), CGRectGetMinY(history6svgGroup) + 0.26316 * CGRectGetHeight(history6svgGroup))];
                [bezierPath closePath];
                bezierPath.miterLimit = 4;

                [fillColor setFill];
                [bezierPath fill];
            }
        }


        //// Group 4
        {
        }


        //// Group 5
        {
        }


        //// Group 6
        {
        }


        //// Group 7
        {
        }


        //// Group 8
        {
        }


        //// Group 9
        {
        }


        //// Group 10
        {
        }


        //// Group 11
        {
        }


        //// Group 12
        {
        }


        //// Group 13
        {
        }


        //// Group 14
        {
        }


        //// Group 15
        {
        }


        //// Group 16
        {
        }


        //// Group 17
        {
        }


        //// Group 18
        {
        }
    }
}

+ (void)drawCanvas2WithFrame: (CGRect)frame
{
    //// Color Declarations
    UIColor* fillColor2 = [UIColor colorWithRed: 0.4 green: 0.4 blue: 0.4 alpha: 1];


    //// Subframes
    CGRect notepads1svgGroup = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.05490 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.02336 + 0.4) + 0.1, floor(CGRectGetWidth(frame) * 0.95131 + 0.33) - floor(CGRectGetWidth(frame) * 0.05490 + 0.5) + 0.17, floor(CGRectGetHeight(frame) * 0.96661 - 0.24) - floor(CGRectGetHeight(frame) * 0.02336 + 0.4) + 0.64);


    //// notepads1.svg Group
    {
        //// Group 2
        {
            //// Bezier Drawing
            UIBezierPath* bezierPath = UIBezierPath.bezierPath;
            [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.97492 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.92071 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.92071 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.03362 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.88728 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.92071 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.01505 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.90576 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.85385 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.03362 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.86880 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.85385 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.01505 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.85385 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.80705 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.80705 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.03362 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.77362 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.80705 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.01505 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.79206 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.74017 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.03362 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.75516 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.74017 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.01505 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.74017 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.69341 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.69341 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.03362 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.65998 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.69341 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.01505 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.67843 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.62653 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.03362 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.64152 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.62653 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.01505 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.62653 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.57974 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.57974 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.03362 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.54630 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.57974 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.01505 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.56479 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.51287 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.03362 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.52782 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.51287 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.01505 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.51287 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.46607 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.46607 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.03362 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.43263 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.46607 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.01505 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.45109 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.39919 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.03362 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.41418 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.00000 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.39919 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.01505 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.39919 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.34912 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.32405 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.08336 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.33529 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.32405 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.06944 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.32405 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.43295 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.37420 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.38253 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.37420 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.10857 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.39919 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.10857 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.39919 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.13244 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.43263 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.39919 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.15101 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.41418 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.46607 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.13244 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.45109 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.46607 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.15101 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.46607 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.10857 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.51287 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.10857 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.51287 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.13244 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.54630 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.51287 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.15101 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.52782 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.57974 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.13244 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.56479 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.57974 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.15101 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.57974 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.10857 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.62653 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.10857 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.62653 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.13244 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.65998 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.62653 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.15101 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.64152 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.69341 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.13244 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.67843 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.69341 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.15101 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.69341 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.10857 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.74017 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.10857 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.74017 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.13244 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.77362 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.74017 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.15101 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.75516 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.80705 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.13244 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.79206 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.80705 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.15101 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.80705 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.10857 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.85385 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.10857 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.85385 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.13244 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.88728 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.85385 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.15101 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.86880 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.92071 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.13244 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.90576 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.16605 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.92071 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.15101 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.92071 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.10857 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.94985 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.10857 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.94985 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.94958 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.37421 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.94958 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.37421 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.74359 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.32405 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.79402 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.32405 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.97479 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.34912 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 1.00000 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.32405 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.98871 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.33529 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 1.00000 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.97492 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 1.00000 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 1.00000 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.97479 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.98877 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 1.00000 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 1.00000 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.98871 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 1.00000 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.08336 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.97492 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 1.00000 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.06944 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.98877 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.05815 * CGRectGetHeight(notepads1svgGroup))];
            [bezierPath closePath];
            bezierPath.miterLimit = 4;

            [fillColor2 setFill];
            [bezierPath fill];


            //// Bezier 2 Drawing
            UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
            [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.63257 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.41691 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.68064 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.28311 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.67477 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.25671 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.68393 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.27390 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.68165 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.26362 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.64851 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.25082 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.66791 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.24979 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.65766 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.24750 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.51541 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.29919 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.51034 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.30508 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.51195 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.30045 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.50881 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.30246 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.02908 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.78886 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.00000 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.84938 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.00888 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.80503 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.00000 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.82651 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.02501 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.90994 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.00000 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.87224 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.00888 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.89376 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.08523 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.93504 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.04107 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.92612 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.06249 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.93504 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.14964 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.90994 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.10802 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.93504 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.12938 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.92612 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.63084 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.42617 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.63257 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.41691 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.62931 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.42356 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.63134 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.42039 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path closePath];
            [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.11004 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.87429 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.06047 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.87429 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.09678 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.88762 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.07373 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.88762 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.05015 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.84938 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.05381 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.86763 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.05015 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.85877 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.06040 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.82452 * CGRectGetHeight(notepads1svgGroup)) controlPoint1: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.05015 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.83999 * CGRectGetHeight(notepads1svgGroup)) controlPoint2: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.05381 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.83116 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.07971 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.80512 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.12927 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.85494 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.11004 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.87429 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path closePath];
            [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.15705 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.83117 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.10749 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.78135 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.53399 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.35263 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.58355 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.40244 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.15705 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.83117 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path closePath];
            [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.59567 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.37124 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.56086 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.33630 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.59973 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.32218 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.60969 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.33218 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(notepads1svgGroup) + 0.59567 * CGRectGetWidth(notepads1svgGroup), CGRectGetMinY(notepads1svgGroup) + 0.37124 * CGRectGetHeight(notepads1svgGroup))];
            [bezier2Path closePath];
            bezier2Path.miterLimit = 4;

            [fillColor2 setFill];
            [bezier2Path fill];
        }


        //// Group 3
        {
        }


        //// Group 4
        {
        }


        //// Group 5
        {
        }


        //// Group 6
        {
        }


        //// Group 7
        {
        }


        //// Group 8
        {
        }


        //// Group 9
        {
        }


        //// Group 10
        {
        }


        //// Group 11
        {
        }


        //// Group 12
        {
        }


        //// Group 13
        {
        }


        //// Group 14
        {
        }


        //// Group 15
        {
        }


        //// Group 16
        {
        }


        //// Group 17
        {
        }
    }
}

@end
