# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'WeddingGram' do

pod 'Parse', '~> 1.7'

end

target 'WeddingGramTests' do

end

