//
//  StyleKit.h
//  WeddingGram
//
//  Created by Ade Ijidakinro on 4/28/15.
//  Copyright (c) 2015 Dephyned. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Drawing Methods
+ (void)drawFlowerWithFrame: (CGRect)frame;
+ (void)drawVideoWithFrame: (CGRect)frame;
+ (void)drawCameraWithFrame: (CGRect)frame;
+ (void)drawTextWithFrame: (CGRect)frame;
+ (void)drawEyeWithFrame: (CGRect)frame;
+ (void)drawHomeWithFrame: (CGRect)frame;
+ (void)drawSmallVideoIcon;

@end
